# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true      
        
    - name: Install Toolchains
      run: |
        sudo apt install \
        git build-essential libsdl2-2.0.0 \
        python3-click python3-numpy python3-pexpect \
        python3-pil python3-pip python3-serial
        pip3 install --user pysdl2
        wget https://www.nordicsemi.com/api/sitecore/Products/DownloadPlatform --post-data=fileid=8F19D314130548209E75EFFADD9348DB -O cli-tools.tar
        tar -xv -f cli-tools.tar
        echo "::add-path::$GITHUB_WORKSPACE/mergehex"
        npm install --global xpm
        xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest
        echo "::add-path::`echo $HOME/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/*/.content/bin`"
        ./micropython/ports/nrf/drivers/bluetooth/download_ble_stack.sh
        
    - name: Build Project
      run: |
        make submodules BOARD=pinetime all
        make softdevice BOARD=pinetime all
        
    #- name: Build Firmware
      #run: make -j `nproc` BOARD=pinetime all
      
    - uses: actions/upload-artifact@v2
      with:
        name: Upload Artifacts
        path: build-pinetime/
